# fly.toml app configuration file generated for jerma-clips on 2025-08-02T00:30:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jerma-clips'
primary_region = 'lax'

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[http_service.concurrency]
type = "requests"
soft_limit = 20
